# Problem 1

In [2]:
import numpy as np

In [3]:
def prob1(A,B):
    return np.dot(A,B)
A=np.array([[3,-1,4],[1,5,-9]])
B=np.array([[2,6,-5,3],[5,-8,9,7],[9,-2,-3,-3]])
prob1(A,B)

array([[ 37,  18, -36, -10],
       [-54, -16,  67,  65]])

# Problem 2

In [88]:
def prob2(A):
    return -np.dot(np.dot(A,A),A)+9*np.dot(A,A)-15*A
A=np.array([[3,1,4],[1,5,9],[-5,3,1]])
prob2(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Problem 3

In [3]:
def prob3(A,B):
       return np.dot(np.dot(A,B),A)
X=np.ones((7,7))
I=np.eye(7)
A=np.triu(X)
B=-np.tril(X)+5*(np.triu(X)-I)
T=prob3(A,B)
T=T.astype(np.int64)
prob3(A,B)

array([[ -7.,  -8.,  -3.,   8.,  25.,  48.,  77.],
       [ -6., -12., -12.,  -6.,   6.,  24.,  48.],
       [ -5., -10., -15., -14.,  -7.,   6.,  25.],
       [ -4.,  -8., -12., -16., -14.,  -6.,   8.],
       [ -3.,  -6.,  -9., -12., -15., -12.,  -3.],
       [ -2.,  -4.,  -6.,  -8., -10., -12.,  -8.],
       [ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.]])

# Problem 4

In [33]:
def prob4(A):
    D=np.copy(A)
    mask=D<0
    D[mask]=0
    return D
#test:
A=([[-2,3,-4,5]])
print(prob4(A))

[[0 3 0 5]]


# Problem 5

In [78]:
def prob5(A,B,C):
    D=np.hstack((np.zeros((3,3)),A.T,np.eye(3)))
    E=np.hstack((A,np.zeros((2,2)),np.zeros((2,3))))
    F=np.hstack((B,np.zeros((3,2)),C))
    return np.vstack((D,E,F))
A=np.transpose(np.arange(6).reshape((3,2)))
B=np.tril(3*np.ones(3))
C=-2*np.eye(3)
print((prob5(A,B,C)))

[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2. -0. -0.]
 [ 3.  3.  0.  0.  0. -0. -2. -0.]
 [ 3.  3.  3.  0.  0. -0. -0. -2.]]


# Problem 6

In [64]:
def prob6(A):
    D=np.copy(A)
    D=D.sum(axis=1)
    n=len(A[:,1])
    E=D.reshape((n,1))
    return np.divide(A,E)
#test:
A=np.array([[1,2,3],[4,5,6]])
prob6(A)

array([[ 0.16666667,  0.33333333,  0.5       ],
       [ 0.26666667,  0.33333333,  0.4       ]])

# Problem 7

In [77]:
def prob7(grid):
    rowmax=np.max(grid[:,:-3]*grid[:,1:-2]*grid[:,2:-1]*grid[:,3:])
    columnmax=np.max(grid[:-3,:]*grid[1:-2,:]*grid[2:-1,:]*grid[3:,:])
    rdiagmax=np.max(grid[:-3,:-3]*grid[1:-2,1:-2]*grid[2:-1,2:-1]*grid[3:,3:])
    ldiagmax=np.max(grid[:-3,3:]*grid[1:-2,2:-1]*grid[2:-1,1:-2]*grid[3:,:-3])   
    return np.max([rowmax,columnmax,rdiagmax,ldiagmax])
grid = np.load("grid.npy")
prob7(grid)


70600674